### ISSUE TITLE
which version of realistic vision do you use?

### ISSUE THREAD

**Issue by fengkai8375** [Dominux/SD_deepnude#1]
May I ask which version of realistic vision do you use? Can you give out the model link or download url?

Because when I use SG161222/Realistic_Vision_V1.4 I got this error

```
ValueError: Incorrect configuration settings! The config of `pipeline.unet`: FrozenDict([('sample_size', 64), ('in_channels', 4), ('out_channels', 4), ('center_input_sample', False), ('flip_sin_to_cos', True), ('freq_shift', 0), ('down_block_types', ['CrossAttnDownBlock2D', 'CrossAttnDownBlock2D', 'CrossAttnDownBlock2D', 'DownBlock2D']), ('mid_block_type', 'UNetMidBlock2DCrossAttn'), ('up_block_types', ['UpBlock2D', 'CrossAttnUpBlock2D', 'CrossAttnUpBlock2D', 'CrossAttnUpBlock2D']), ('only_cross_attention', False), ('block_out_channels', [320, 640, 1280, 1280]), ('layers_per_block', 2), ('downsample_padding', 1), ('mid_block_scale_factor', 1), ('act_fn', 'silu'), ('norm_num_groups', 32), ('norm_eps', 1e-05), ('cross_attention_dim', 768), ('attention_head_dim', 8), ('dual_cross_attention', False), ('use_linear_projection', False), ('class_embed_type', None), ('num_class_embeds', None), ('upcast_attention', False), ('resnet_time_scale_shift', 'default'), ('_class_name', 'UNet2DConditionModel'), ('_diffusers_version', '0.10.2'), ('_name_or_path', 'C:\\Users\\Admin/.cache\\huggingface\\diffusers\\models--SG161222--Realistic_Vision_V1.3\\snapshots\\a427e813a6d4d6fef7dc2b36d5092f3281a8b998\\unet')]) expects 4 but received `num_channels_latents`: 4 + `num_channels_mask`: 1 + `num_channels_masked_image`: 4 = 9. Please verify the config of `pipeline.unet` or your `mask_image` or `image` input.
```
V2.0 and V1.3 do the same result.

Thanks.

**Comment by cemalcelik** [comment]
how can ı run this script ? I try the python run.py input.png and not working..

**Comment by Dominux** [comment]
**The project isn't ready to run as it is yet!**, it can be run with some preparations only
I created the project a couple of weeks ago and unfortunately don't remember all the actions I made to make the model work. It included replacing original RealisticVision config files with stable-diffusion-inpainting ones and some changes in other config files

**Comment by fengkai8375** [comment]
Thanks for your response.

> **The project isn't ready to run as it is yet!**, it can be run with some preparations only
> I created the project a couple of weeks ago and unfortunately don't remember all the actions I made to make the model work. It included replacing original RealisticVision config files with stable-diffusion-inpainting ones and some changes in other config files

**Comment by Dominux** [comment]
For all the ones who were intended to run it, I have good news -- I updated the repo so you can finally run it
