### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by faqeoda** [Dominux/SD_deepnude#11]
I followed all the instructions, the bot does not respond to commands at all, but everything is configured and running correctly for me
![bfb526f4-91c7-4a4e-bbb4-a0c7c2f22d60](https://github.com/Dominux/SD_deepnude/assets/144239076/f139b6cb-c5fe-4be8-ac07-bd2a73a1adbb)
![d1b09407-55ab-4623-907d-1be8ca055d30](https://github.com/Dominux/SD_deepnude/assets/144239076/18f740ae-91fd-4512-bbb2-6678ecb924e3)

**Comment by faqeoda** [comment]
What could be the problem? please help..

**Comment by Dominux** [comment]
Ty kto takoy? Davai 
![image](https://github.com/Dominux/SD_deepnude/assets/55978340/104b2cee-d390-4c96-9b47-ab36daec4503)
