### ISSUE TITLE
 The bot does not use the settings from sd_api.ru

### ISSUE THREAD

**Issue by faqeoda** [Dominux/SD_deepnude#12]
async with httpx.AsyncClient(timeout=None) as client:
        r = await client.post(
            "http://localhost:7861/sdapi/v1/img2img",
            json={
                "init_images": [image],
                "resize_mode": "1",
                "denoising_strength": 0.9,
                "mask": mask,
                "mask_blur": 8,
                "prompt": "fully nude fit girl, big perfect sexy breast, hyper detailed, intricate skin texture, (goosebumps:1.3)",
                "negative_prompt": "(deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation",
                "steps": 26,
                "sampler_index": "DPM++ SDE Karras",
                "inpaint_full_res": False,
                
        how to adjust these settings all climbed, from here he does not see them?

**Comment by Dominux** [comment]
What do u mean? Which settings?

**Comment by faqeoda** [comment]
yes that's what I meant, thanks

**Comment by faqeoda** [comment]
doesn't want to c
![Безымянный](https://github.com/Dominux/SD_deepnude/assets/144239076/25d132bc-e1e5-4598-b1f9-41edc0439796)
hange anything, this error even if you copy the basic script

**Comment by Dominux** [comment]
The error happens on your SD side, u send the request directly to it's API

**Comment by faqeoda** [comment]
this is understandable, but I can't find how to fix it anywhere

**Comment by Dominux** [comment]
It's not my problem dude, open issues in the SD repo

**Comment by faqeoda** [comment]
ok

**Comment by faqeoda** [comment]
Can you recommend a good Safetensor?

**Comment by Dominux** [comment]
Depends on wht u want it to. In case of the most realistic results it's IMHO [epicPhotoGasm](https://civitai.com/models/132632?modelVersionId=162465)

**Comment by faqeoda** [comment]
I've been experimenting for 10 hours to achieve a better result with samplers and settings, I want to catch up with a similar hyped project, I'll try this one, thank you
