### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by TriniHam** [Dominux/SD_deepnude#17]
Traceback (most recent call last):
  File "bot.py", line 13, in <module>
    API_TOKEN = os.environ["12345678900:abcdefghijklmnopqrstuvwxyz"]
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: '12345678900:abcdefghijklmnopqrstuvwxyz'

Line 13 of bot.py:

```
# Bot token can be obtained via https://t.me/BotFather
API_TOKEN = os.environ["12345678900:abcdefghijklmnopqrstuvwxyz"]
```

**Comment by Dominux** [comment]
hey sup dumb, it's not the original code

[here's the line ya tryna refer to](https://github.com/Dominux/SD_deepnude/blob/main/bot.py#L13)

**Comment by TriniHam** [comment]
Hey, so what I'm referencing is my  API TOKEN, was it suppose to go there?

**Comment by Dominux** [comment]
have ya tried to google env vars at the end of the day?

**Comment by TriniHam** [comment]
> have ya tried to google env vars at the end of the day?

Yes, but is it like Var name: export API_TOKEN and var value:12345678900:abcdefghijklmnopqrstuvwxyz ?? Cuz I'm lost

**Comment by TriniHam** [comment]
> have ya tried to google env vars at the end of the day?



> > have ya tried to google env vars at the end of the day?
> 
> Yes, but is it like Var name: export API_TOKEN and var value:12345678900:abcdefghijklmnopqrstuvwxyz ?? Cuz I'm lost (BTW I only know env var to be in windows settings)

So I tried that it worked but here's the local AUTOMATIC1111 webui,

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-NVidia-GPUs

I'm unable to get the --nowebui
