### ISSUE TITLE
Incomplete Command

### ISSUE THREAD

**Issue by sahilkundu** [Dominux/SD_deepnude#2]
There are no command given after python3 bot.py.
Please tell how it work after bot starting.

**Comment by Dominux** [comment]
Have you created telegram bot?

**Comment by sahilkundu** [comment]
I have created telegram bot,
also export API_TOKEN
also use /start command

How can be use after /start command.

**Comment by Dominux** [comment]
Send an image of a girl in bikini to the bot

**Comment by sahilkundu** [comment]
Already sent image bro in the bot but no further processing.

**Comment by Dominux** [comment]
No messages in console?

**Comment by sahilkundu** [comment]
Yes there are message in the console like that 
INFO:aiogram.event:Update id=xxxx9xxxx is not handled. Duration 1 ms by bot id=xxxxxx09xx

**Comment by Dominux** [comment]
U send an image as a photo?
Send chat screenshot for better understanding

**Comment by xuxuxu222** [comment]
how to run bot  ?on  SD in google colab

**Comment by Dominux** [comment]
@xuxuxu222, aint ya already running?
