### ISSUE TITLE
can't find cm.lib file anywhere

### ISSUE THREAD

**Issue by millysecurity** [Dominux/SD_deepnude#4]
I found checkpoint files but googling didn't give any results

**Comment by Deaks123** [comment]
Yea same no clue what it is

**Comment by Dominux** [comment]
search for deepnude weights in the internet, there are some places I was founding just a month ago

**Comment by githubber6000** [comment]
there are no deepnude weights anywhere anymore tho, could you include google drive link?

**Comment by githubber6000** [comment]
> I found checkpoint files but googling didn't give any results

did you get the thing to work?

**Comment by frightened-2011** [comment]
i have the links lmao

**Comment by DARKM00N1337** [comment]
Search any old deepnude source code and download it

**Comment by Dominux** [comment]
They can barely do so lmao

Anyway not my problem
